# ?????????????????????????????????????
#   SysLens Configuration File
# ?????????????????????????????????????

# General
app.name                 = SysLens
app.version              = 1.0.0

# Monitor
monitor.refresh.seconds  = 5
monitor.show.banner      = true

# Alerts ? CPU
alert.cpu.warn           = 75.0
alert.cpu.critical       = 90.0

# Alerts ? RAM
alert.ram.warn           = 75.0
alert.ram.critical       = 90.0

# Alerts ? Disk
alert.disk.warn          = 80.0
alert.disk.critical      = 95.0

# Alerts ? Temperature (°C)
alert.temp.warn          = 75.0
alert.temp.critical      = 85.0

# Export
export.dir               = syslens-reports
export.default.format    = text

# Logging
log.enabled              = false
log.dir                  = syslens-logs
log.debug                = false

# Process
process.top.count        = 10

# Display
display.show.banner      = true
display.color.enabled    = true