/**
 * HtmlFormatter.java
 *
 * Author: Abhishek Shukla
 * Version: 1.0.0
 * Last Updated: 2026-05-05
 *
 * Description:
 *   HtmlFormatter is an OutputFormatter implementation that converts
 *   a SystemSnapshot into a styled HTML report. It organizes results
 *   into sections with headers and preformatted text blocks.
 *
 * Purpose:
 *   - Provide a visually appealing, web-friendly format for SysLens reports.
 *   - Support contributors by offering a template that can be extended
 *     with custom CSS or additional metadata.
 *   - Demonstrate integration of Java string formatting with HTML output.
 *
 * Notes for Contributors:
 *   - Uses inline CSS for styling; consider external stylesheets for larger projects.
 *   - Sections are generated dynamically from snapshot text results.
 *   - Extend by adding charts, tables, or interactive elements.
 *   - Footer includes SysLens version for traceability.
 */

package com.aurexiris.syslens.output;

import com.aurexiris.syslens.core.SystemSnapshot;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;

public class HtmlFormatter implements OutputFormatter {

    /**
     * Format the given SystemSnapshot into a styled HTML report.
     * @param snapshot the system snapshot containing results
     * @return HTML string representing the report
     */
    @Override
    public String format(SystemSnapshot snapshot) {
        String timestamp = LocalDateTime.now()
                .format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));

        StringBuilder sections = new StringBuilder();
        for (Map.Entry<String, String> entry : snapshot.getTextResults().entrySet()) {
            sections.append("""
                    <div class="section">
                        <h2>%s</h2>
                        <pre>%s</pre>
                    </div>
                    """.formatted(
                    entry.getKey(),
                    entry.getValue()
            ));
        }

        return """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width">
                    <title>SysLens Report</title>
                    <style>
                        body {
                            background: #0d1117;
                            color: #c9d1d9;
                            font-family: 'Courier New', monospace;
                            padding: 20px;
                            margin: 0;
                        }
                        h1 {
                            color: #58a6ff;
                            text-align: center;
                            border-bottom: 2px solid #30363d;
                            padding-bottom: 10px;
                        }
                        .timestamp {
                            text-align: center;
                            color: #8b949e;
                            margin-bottom: 30px;
                            font-size: 0.9em;
                        }
                        .section {
                            background: #161b22;
                            border: 1px solid #30363d;
                            border-radius: 8px;
                            padding: 16px;
                            margin-bottom: 20px;
                        }
                        h2 {
                            color: #f0883e;
                            margin-top: 0;
                            font-size: 1em;
                            text-transform: uppercase;
                            letter-spacing: 1px;
                        }
                        pre {
                            margin: 0;
                            white-space: pre-wrap;
                            font-size: 0.85em;
                            color: #c9d1d9;
                        }
                        .footer {
                            text-align: center;
                            color: #8b949e;
                            font-size: 0.8em;
                            margin-top: 30px;
                        }
                    </style>
                </head>
                <body>
                    <h1>SysLens — System Report</h1>
                    <p class="timestamp">Generated: %s</p>
                    %s
                    <p class="footer">Generated by SysLens v1.0.0</p>
                </body>
                </html>
                """.formatted(timestamp, sections);
    }
}
