org.slf4j.simpleLogger.defaultLogLevel=off
org.slf4j.simpleLogger.log.oshi=off
org.slf4j.simpleLogger.log.com.profesorfalken=off
org.slf4j.simpleLogger.log.com.sun.jna=off
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false